apiVersion: v1
kind: Service
metadata:
  name: analysis-engine
  namespace: gpu
  labels:
    name: analysis-engine
spec:
  type: NodePort
  ports:
  - port: 9322
    targetPort: 9322
    nodePort: 32552
    protocol: TCP
  selector:
    name: analysis-engine