apiVersion: v1
kind: ServiceAccount
metadata:
  name: analysis-engine
  namespace: gpu
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: analysis-engine
  namespace: gpu
subjects:
- kind: ServiceAccount
  name: analysis-engine
  namespace: gpu
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: analysis-engine
  namespace: gpu
  labels:
    name: analysis-engine
spec:
  type: NodePort
  ports:
  - port: 9322
    targetPort: 9322
    nodePort: 32552
    protocol: TCP
  selector:
    name: analysis-engine
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keti-analysis-engine
  namespace: gpu
spec:
  selector:
    matchLabels:
      name: analysis-engine
  replicas: 1
  template:
    metadata:
      labels:
        name: analysis-engine
    spec:
      nodeName: c1-master
      serviceAccountName: analysis-engine
      imagePullSecrets: 
      - name: regcred
      restartPolicy: Always
      containers:
      - name: analysis-engine
        image: ketidevit2/keti-analysis-engine:v1.0
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName


